sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: 80280358649-hm15q6p5a80eucd3ofo9qrq52tjha4pu.apps.googleusercontent.com
      secret: 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
    callback:
      url: http://localhost:3000/members/auth/google/callback
    token:
      url: https://oauth2.googleapis.com/token
  kakao:
    url: https://kauth.kakao.com/oauth/authorize
    client:
      id: 749543c2fcac96b16a784cd0579d6dc0
      secret: aRgfTJgUFdFJherSYizH3Xq3bfl9p8zZ
    callback:
      url: http://localhost:3000/members/auth/kakao/callback
    token:
      url: https://kauth.kakao.com/oauth/token
  naver:
    url: https://nid.naver.com/oauth2.0/authorize
    client:
      id: MjpqAsnF4kQLyR6YjJ3A
      secret: 22KHG5IT3G
    callback:
      url: http://localhost:3000/members/auth/naver/callback
    token:
      url: https://nid.naver.com/oauth2.0/token